[package]
name = "karte-os-kernel"
version = "0.1.0"
edition = "2024"

[features]
default = []
test_mode = []

[dependencies]
riscv = "0.16"
riscv-rt = "0.17"
sbi = "0.3"
buddy_system_allocator = "0.13"
spin = "0.12"
bitflags = "2.11"
virtio-drivers = { version = "0.13.0", features = ["alloc"] }
starry-fatfs = { version = "0.4.1-preview.2", default-features = false, features = ["alloc", "lfn"] }
