[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]

[alias]
kbuild = "build --release -p karte-os-kernel"
krun = "run --release -p karte-os-kernel"
